### PR TITLE
Some more deaths

### PR DESCRIPTION
**Pull request by SquirrelJay**
Hey Troy its Squirrel I added

 4 new [kill_unarmed deaths] 

2 new [kill_unarmed_insane deaths]

2 new [eats]
 
1 new [think_rare]

2 new in [think]

idk why it says 6 deletions i didn't delete any of your work?

### CODE REVIEW

**Comment by triverske** [comment]
Hey Squirrel, it says something is a deletion whenever it is changed. In this case you changed the "total" values so it thinks you deleted something. Excellent additions, congrats on your first pull request!

**Comment by SquirrelJay** [comment]
Will these show up in the game now?

**Comment by triverske** [comment]
They'll show up the next time the game updates. (Likely tomorrow night, Friday at the latest)

Alternatively, if you ever want to test these changes you should download Gamemaker and compile the game yourself. This will let you play the game before I update it.

**Comment by SquirrelJay** [comment]
I still new to this which branch should i be using patch-1 or master since you converted it into master?

**Comment by triverske** [comment]
I believe you use patch one, I'm also new to this so not entirely sure.

**Comment by SquirrelJay** [comment]
Okay i will use Patch-1 i'm going to put some more stuff in today so i will see what happens :+1: :D

**Pull request merged**
